language: node_js
sudo: true
before_install:
- openssl aes-256-cbc -K $encrypted_a8a796aec5ba_key -iv $encrypted_a8a796aec5ba_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- npm install
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: scp -r dist/* root@zhangmengke.cn:/home/wwwroot/brb.zhangmengke.cn/
  on:
    branch: master
